repos:
  - repo: local
    hooks:
      - id: full-project-check
        name: Full project check
        entry: ./scripts/check.sh
        language: system
        pass_filenames: false
        stages:
          - pre-commit

      - id: archive-successful-commit
        name: Archive successful commit
        entry: ./scripts/archive.sh
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - post-commit