# Generated by Django 6.1.1 on 2026-09-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my1stapp", "0004_alter_userprofile_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-gb", "English (UK)"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                ],
                default="en-gb",
                max_length=10,
            ),
        ),
    ]
