# Generated by Django 6.1.1 on 2026-09-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiclientcredential",
            name="client_secret",
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
